### ISSUE TITLE
Dollar signs are escaped in ENV

### ISSUE THREAD

**Issue by bgamari** [softwarefactory-project/dhall-containerfile#3]
The following
```dhall
let CF = https://raw.githubusercontent.com/softwarefactory-project/dhall-containerfile/e3ea2f2e02bd979b4255dfbc5d7086dbbfcbc6c2/package.dhall
in CF.render (CF.env (toMap { PATH = "/usr/bin:$PATH" }))
```
produces
```bash
$ dhall text < test.dhall
ENV PATH="/usr/bin:\u0024PATH"
```

Note the escaped dollar sign. This appears to be due to the use of `Text/show` in https://github.com/softwarefactory-project/dhall-containerfile/blob/master/Containerfile/render/textEntry.dhall.

**Comment by TristanCacqueray** [comment]
Arg I see. `Text/show` was used to support the `ENV myName="John Doe"` syntax, but turns out using `ENV myName John Doe` yield the same results according to https://docs.docker.com/engine/reference/builder/#env .
